# Generated by Django 3.2.6 on 2021-09-21 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=250)),
                ('status', models.IntegerField(choices=[(1, 'TODO'), (2, 'DONE')], default=1)),
            ],
        ),
    ]
